#!/bin/ksh
# pkgadd - merge tarball to root

die() {
    printf 'error: %s\n' "${1}" >&2
    exit ${2:-1}
}

log() {
    printf 'log: %s\n' "${1}" >&2
}

usage() {
    cat << EOF
usage:
pkgadd [opts] <pkgtar>
    -f  force package installation
    -u  upgrade package
    -r  use alternate root
    -h  print this message
EOF
}

parse_args() {
    while [ "${1}" ]; do
        case ${1} {
        (-h) usage              ;;
        (-f) force=1            ;;
        (-u) upgrade=1          ;;
        (-r) root="${2}"; shift ;;
        }
    shift
    done
}

PKGADD_IGNORE=("etc/*")
